/* ============================================================
   BAI1-DATA.JS — Dữ liệu câu hỏi Bài 1
   Được load trước quiz-engine.js
   Gán mảng vào window.QUIZ_DATA để engine đọc
   ============================================================ */

window.QUIZ_DATA = [
  {
    id: 1,
    text: "Những nhà tư tưởng tiêu biểu của chủ nghĩa xã hội không tưởng phê phán đầu thế kỷ XIX là ai?",
    options: [
      "Xanh Ximông, Giăng Mêliê, Rôbớt Ôoen",
      "Xanh Ximông, Sắclơ Phuriê, Rôbớt Ôoen",
      "Xanh Ximông, Sắclơ Phuriê, G. Mably",
      "Grắccơ Babớp, Xanh Ximông, Sắclơ Phuriê",
    ],
    correct: [1],
  },
  {
    id: 2,
    text: "Tác phẩm nào đánh dấu sự ra đời của chủ nghĩa xã hội khoa học?",
    options: [
      "Bộ tư bản",
      "Tình cảnh nước Anh",
      "Tuyên ngôn của Đảng Cộng sản",
      "Góp phần phê phán triết học pháp quyền của Hêghen – Lời nói đầu",
    ],
    correct: [2],
  },
  {
    id: 3,
    text: "Phát kiến nào của C.Mác và Ph.Ăngghen chỉ ra sự diệt vong về kinh tế của chủ nghĩa tư bản?",
    options: [
      "Học thuyết về giá trị thặng dư",
      "Chủ nghĩa duy vật biện chứng",
      "Chủ nghĩa duy vật lịch sử",
      "Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân",
    ],
    correct: [0],
  },
  {
    id: 4,
    text: "Phát kiến nào của C.Mác và Ph.Ăngghen chỉ ra những hạn chế có tính lịch sử của chủ nghĩa xã hội không tưởng?",
    options: [
      "Chủ nghĩa duy vật lịch sử",
      "Học thuyết về giá trị thặng dư",
      "Chủ nghĩa duy vật biện chứng",
      "Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân",
    ],
    correct: [3],
  },
  {
    id: 5,
    text: "Đâu là nhân tố chủ quan quan trọng nhất để giai cấp công nhân thực hiện thắng lợi sứ mệnh lịch sử của mình?",
    options: [
      "Sự phát triển của giai cấp công nhân về chất lượng",
      "Đảng Cộng sản",
      "Liên minh giai cấp công nhân với giai cấp nông dân",
      "Sự phát triển của giai cấp công nhân về số lượng",
    ],
    correct: [1],
  },
  {
    id: 6,
    text: 'Ph.Ăngghen đã đánh giá: "Hai phát hiện vĩ đại này đã đưa chủ nghĩa xã hội trở thành một khoa học". Hai phát kiến đó là gì?',
    options: [
      "Chủ nghĩa duy vật biện chứng và chủ nghĩa duy vật lịch sử",
      "Học thuyết giá trị thặng dư – Chủ nghĩa duy vật lịch sử",
      "Sứ mệnh lịch sử của giai cấp công nhân – Chủ nghĩa duy vật lịch sử",
      "Sứ mệnh lịch sử của giai cấp công nhân – Học thuyết giá trị thặng dư",
    ],
    correct: [1],
  },
  {
    id: 7,
    text: "Xét trong quan hệ sản xuất tư bản chủ nghĩa giai cấp công nhân là:",
    options: [
      "Giai cấp nghèo khổ nhất",
      "Giai cấp không có tư liệu sản xuất, đi làm thuê cho nhà tư bản, bị nhà tư bản bóc lột giá trị thặng dư",
      "Giai cấp tạo ra của cải cho xã hội",
      "Giai cấp có số lượng đông trong dân cư",
    ],
    correct: [1],
  },
  {
    id: 8,
    text: "Đặc điểm sứ mệnh lịch sử của giai cấp công nhân là:",
    options: [
      "Thay thế chế độ sở hữu tư nhân này bằng một chế độ sở hữu tư nhân khác",
      "Thay thế chế độ công hữu này bằng một chế độ công hữu khác",
      "Thay thế chế độ chiếm hữu nô lệ bằng chế độ xã hội chủ nghĩa",
      "Xóa bỏ triệt để chế độ tư hữu về tư liệu sản xuất",
    ],
    correct: [3],
  },
  {
    id: 9,
    text: "Giai cấp công nhân Việt Nam ra đời vào thời gian nào?",
    options: [
      "Trong cuộc khai thác thuộc địa lần thứ nhất của thực dân Pháp",
      "Trong cuộc khai thác thuộc địa lần thứ hai của thực dân Pháp",
      "Trước khi thực dân Pháp xâm lược Việt Nam.",
      "Những năm đầu thế kỷ 19.",
    ],
    correct: [0],
  },
  {
    id: 10,
    text: 'Điền từ còn thiếu vào chỗ trống "Giai cấp công nhân Việt Nam thực hiện lãnh đạo cách mạng thông qua đội tiên phong của nó là (...)"',
    options: [
      "Tổ chức công đoàn",
      "Tổng liên đoàn lao động Việt Nam",
      "Mặt trận tổ quốc Việt Nam",
      "Đảng Cộng sản Việt Nam",
    ],
    correct: [3],
  },
  {
    id: 11,
    text: "Nội dung trực tiếp về văn hoá tư tưởng thể hiện sứ mệnh lịch sử của giai cấp công nhân Việt Nam là:",
    options: [
      "Xây dựng hệ giá trị và con người Việt Nam",
      "Xây dựng nền văn hoá Việt Nam tiên tiến, đậm đà bản sắc dân tộc",
      "Xây dựng nền giáo dục hiện đại",
      "Xây dựng con người mới xã hội chủ nghĩa",
    ],
    correct: [1],
  },
  {
    id: 12,
    text: "Vấn đề nổi bật nhất đối với việc thực hiện sứ mệnh lịch sử của giai cấp công nhân Việt Nam hiện nay là gì?",
    options: [
      "Nắm vững khoa học và công nghệ",
      "Phát huy vai trò và trách nhiệm của lực lượng đi đầu trong sự nghiệp đẩy mạnh công nghiệp hoá, hiện đại hoá đất nước",
      "Lực lượng chủ đạo trong lao động",
      "Tham gia xây dựng nền kinh tế thị trường định hướng xã hội chủ nghĩa",
    ],
    correct: [1],
  },
  {
    id: 13,
    text: 'Theo Ph. Ăngghen: "Thực hiện nhiệm vụ giải phóng thế giới ấy, đó là sứ mệnh lịch sử của...". Hãy chọn đáp án đúng điền vào chỗ trống?',
    options: [
      "Giai cấp tiểu tư sản",
      "Giai cấp nông dân",
      "Giai cấp tư sản",
      "Giai cấp vô sản",
    ],
    correct: [3],
  },
  {
    id: 14,
    text: "Theo C.Mác và Ph.Ăngghen thì đặc điểm nổi bật của giai cấp công nhân là:",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Giai cấp cách mạng và có tinh thần cách mạng triệt để",
      "Lao động bằng phương thức công nghiệp",
      "Có quyền sở hữu toàn bộ tư liệu sản xuất",
      "Làm việc trong nông nghiệp, sử dụng công cụ thủ công",
    ],
    correct: [0, 1],
  },
  {
    id: 15,
    text: "Trong thời kỳ thuộc địa, giai cấp công nhân Việt Nam chủ yếu làm việc trong:",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Nhà máy, hầm mỏ do thực dân Pháp xây dựng",
      "Đồn điền cao su",
      "Hợp tác xã nông nghiệp",
      "Xí nghiệp thủ công truyền thống",
    ],
    correct: [0, 1],
  },
  {
    id: 16,
    text: "Điền từ còn thiếu vào chỗ trống: Giai cấp công nhân và nhân dân lao động là cơ sở..., cơ sở... của Đảng cộng sản, là nguồn bổ sung lực lượng phong phú cho Đảng.",
    options: [
      "Kinh tế - xã hội",
      "Văn hoá - xã hội",
      "Chính trị - xã hội",
      "Giai cấp – xã hội",
    ],
    correct: [2],
  },
  {
    id: 17,
    text: "Hạn chế cơ bản lớn nhất mà giai cấp công nhân Việt Nam hiện nay cần khắc phục là gì?",
    options: [
      "Số lượng còn ít",
      "Trình độ khoa học kỹ thuật chưa cao",
      "Hiệu quả lao động thấp",
      "Tâm lý tiểu nông",
    ],
    correct: [1],
  },
  {
    id: 18,
    text: "Trong các nội dung sau đây thì nội dung nào thuộc về giải pháp xây dựng giai cấp công nhân Việt Nam hiện nay?",
    options: [
      "Xây dựng giai cấp công nhân lớn mạnh, có giác ngộ giai cấp và chính trị vững vàng",
      "Nâng cao nhận thức, kiên định quan điểm giai cấp công nhân là giai cấp lãnh đạo cách mạng thông qua đội tiên phong là Đảng Cộng sản Việt Nam",
      "Xây dựng giai cấp công nhân tăng về số lượng và chất lượng",
      "Coi trọng và giữ vững bản chất giai cấp công nhân và nguyên tắc sinh hoạt Đảng",
    ],
    correct: [1],
  },
  {
    id: 19,
    text: "Điểm then chốt để giúp giai cấp công nhân Việt Nam hiện nay thực hiện thành công sứ mệnh lịch sử của mình là:",
    options: [
      "Trí thức hoá giai cấp công nhân",
      "Coi trọng công tác xây dựng, chỉnh đốn Đảng",
      "Phát triển giai cấp công nhân cả về số lượng và chất lượng",
      "Xây dựng khối liên minh công – nông",
    ],
    correct: [1],
  },
  {
    id: 20,
    text: "Đặc điểm nào sau đây thể hiện đúng bản chất của giai cấp công nhân?",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Có trình độ học vấn thấp, chủ yếu làm việc tay chân",
      "Luôn gắn bó với giai cấp địa chủ và tiểu thương",
      "Có tính tổ chức và kỷ luật cao trong lao động sản xuất",
      "Không sở hữu tư liệu sản xuất, sống bằng lao động làm thuê",
    ],
    correct: [2, 3],
  },
  {
    id: 21,
    text: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là gì?",
    options: [
      "Là những quy luật và tính quy luật chính trị – xã hội của quá trình phát sinh, hình thành và phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa",
      "Là những quy luật hình thành, phát triển và hoàn thiện của các hình thái kinh tế - xã hội.",
      "Là những quy luật văn hoá - xã hội.",
      "Là những quy luật kinh tế",
    ],
    correct: [0],
  },
  {
    id: 22,
    text: "Phạm trù nào được coi là cơ bản nhất và là xuất phát điểm của chủ nghĩa xã hội khoa học?",
    options: [
      "Cách mạng xã hội chủ nghĩa",
      "Sứ mệnh lịch sử của giai cấp công nhân",
      "Chuyên chính vô sản",
      "Giai cấp công nhân",
    ],
    correct: [1],
  },
  {
    id: 23,
    text: "Tìm ý đúng để hoàn thiện luận điểm sau: Cùng với sự phát triển của khoa học và công nghệ ngày càng hiện đại, giai cấp công nhân:",
    options: [
      "Giảm về số lượng và nâng cao về chất lượng.",
      "Giảm về số lượng và có trình độ sản xuất ngày càng cao",
      "Tăng về số lượng và nâng cao về chất lượng",
      "Tăng về số lượng và giảm về chất lượng",
    ],
    correct: [2],
  },
  {
    id: 24,
    text: "Dấu hiệu đánh dấu sự trưởng thành vượt bậc của giai cấp công nhân với tư cách là giai cấp cách mạng là:",
    options: [
      "Sự trưởng thành về trình độ kỹ thuật",
      "Sự trưởng thành về ý thức chính trị",
      "Sự ra đời của Đảng Cộng sản",
      "Sự trưởng thành về trình độ nhận thức",
    ],
    correct: [2],
  },
  {
    id: 25,
    text: "Trong các nội dung sau đây thì nội dung nào thuộc về giải pháp xây dựng giai cấp công nhân Việt Nam hiện nay?",
    options: [
      "Xây dựng giai cấp công nhân lớn mạnh, có giác ngộ giai cấp và chính trị vững vàng",
      "Thực hiện tốt chính sách và pháp luật đối với công nhân và người lao động.",
      "Thực hiện chiến lược xây dựng giai cấp công nhân lớn mạnh, gắn kết chặt chẽ với chiến lược phát triển kinh tế - xã hội, công nghiệp hoá, hiện đại hoá đất nước, hội nhập quốc tế",
      "Coi trọng và giữ vững bản chất giai cấp công nhân và nguyên tắc sinh hoạt Đảng",
    ],
    correct: [2],
  },
  {
    id: 26,
    text: "Điều kiện chủ quan để giai cấp công nhân thực hiện được sứ mệnh lịch sử của mình là:",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Đảng Cộng sản",
      "Sự phát triển của bản thân giai cấp công nhân cả về số lượng và chất lượng",
      "Không cần liên minh với các giai cấp, tầng lớp khác",
      "Sở hữu toàn bộ tư liệu sản xuất trong xã hội",
    ],
    correct: [0, 1],
  },
  {
    id: 27,
    text: "Giai cấp công nhân Việt Nam có đặc điểm gì khác với giai cấp công nhân ở các nước tư bản?",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Sở hữu tư liệu sản xuất trong xã hội",
      "Chịu sự bóc lột của thực dân và phong kiến",
      "Xuất thân từ nông dân là chủ yếu",
      "Không có sự gắn kết với các giai cấp, tầng lớp khác",
    ],
    correct: [1, 2],
  },
  {
    id: 28,
    text: "Xét về phương thức lao động, phương thức sản xuất, giai cấp công nhân mang thuộc tính cơ bản nào?",
    options: [
      "Có số lượng đông nhất trong dân cư.",
      "Là giai cấp tạo ra của cải vật chất làm giàu cho xã hội",
      "Là giai cấp trực tiếp hay gián tiếp vận hành máy móc có tính chất công nghiệp ngày càng hiện đại",
      "Giai cấp có tư liệu sản xuất nhiều nhất",
    ],
    correct: [2],
  },
  {
    id: 29,
    text: "Giai cấp công nhân Việt Nam chủ yếu xuất thân từ tầng lớp nào?",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Tầng lớp tư sản dân tộc",
      "Giai cấp nông dân bị tước đoạt hết ruộng đất",
      "Thợ thủ công bị phá sản",
      "Tầng lớp địa chủ phong kiến",
    ],
    correct: [1, 2],
  },
  {
    id: 30,
    text: 'Câu nói sau đây được viết trong tác phẩm nào: "Giai cấp tư sản, trong quá trình thống trị giai cấp chưa đầy một thế kỷ, đã tạo ra những lực lượng sản xuất nhiều hơn và đồ sộ hơn lực lượng sản xuất của tất cả các thế hệ trước gộp lại"',
    options: [
      "Chống Đuyrinh",
      "Ba nguồn gốc và ba bộ phận cấu thành của chủ nghĩa Mác",
      "Tuyên ngôn của Đảng Cộng sản",
      "Bộ Tư bản",
    ],
    correct: [2],
  },
  {
    id: 31,
    text: 'Kéo thả (đã chuyển thành trắc nghiệm): "Thực hiện sự nghiệp giải phóng thế giới ấy, đó là sứ mệnh lịch sử của ... hiện đại"',
    options: [
      "Giai cấp vô sản",
      "Giai cấp nông dân",
      "Giai cấp tư sản",
      "Tầng lớp trí thức",
    ],
    correct: [0],
  },
  {
    id: 32,
    text: "Điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân bao gồm:",
    note: "Chọn 2 đáp án đúng",
    options: [
      "Địa vị kinh tế của giai cấp công nhân",
      "Địa vị chính trị - xã hội của giai cấp công nhân",
      "Sự phát triển về số lượng và chất lượng của giai cấp công nhân",
      "Sự ra đời của Đảng Cộng sản",
    ],
    correct: [0, 1],
  },
  {
    id: 33,
    text: "Nội dung sứ mệnh lịch sử của giai cấp công nhân Việt Nam hiện nay bao gồm:",
    note: "Chọn 3 đáp án đúng",
    options: [
      "Nội dung văn hóa, tư tưởng",
      "Nội dung chính trị - xã hội",
      "Nội dung kinh tế",
      "Nội dung lý luận",
    ],
    correct: [0, 1, 2],
  },
  {
    id: 34,
    text: "Giai cấp công nhân phát huy vai trò và trách nhiệm của lực lượng đi đầu trong sự nghiệp đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước.",
    options: ["Đúng", "Sai"],
    correct: [0],
  },
  {
    id: 35,
    text: "Chủ nghĩa xã hội khoa học ra đời dựa trên cơ sở của những tiền đề nào?",
    note: "Chọn 2 đáp án đúng nhất",
    options: [
      "Tiền đề khoa lịch sử",
      "Tiền đề khoa học tự nhiên",
      "Tiền đề khoa học xã hội",
      "Tiền đề tư tưởng lý luận",
    ],
    correct: [1, 3],
  },
  {
    id: 36,
    text: "Đảng Cộng sản là nhân tố khách quan quan trọng nhất để giai cấp công nhân thực hiện thắng lợi sứ mệnh lịch sử của mình.",
    options: ["Đúng", "Sai"],
    correct: [1],
  },
  {
    id: 37,
    text: "Giai cấp công nhân Việt Nam hiện nay đã tăng nhanh về số lượng và chất lượng.",
    options: ["Đúng", "Sai"],
    correct: [0],
  },
  {
    id: 38,
    text: "Đảng Cộng sản là ... quan trọng nhất để giai cấp công nhân thực hiện thắng lợi sứ mệnh lịch sử của mình.",
    options: [
      "Nhân tố chủ quan",
      "Nhân tố khách quan",
      "Điều kiện khách quan",
      "Tiền đề lý luận",
    ],
    correct: [0],
  },
  {
    id: 39,
    text: "Giai cấp công nhân là ... của quá trình sản xuất vật chất hiện đại.",
    options: ["Chủ thể", "Khách thể", "Sản phẩm", "Đối tượng"],
    correct: [0],
  },
];
